language: dart
dist: bionic
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor
  - flutter --version
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache